### ISSUE TITLE
release.c For TVOSf_NT, change the yield from -1 (forever) to 100.

### ISSUE THREAD

**Issue by guy-rouillier** [windoze/tvision#3]
For TVOSf_NT, change the yield from -1 (forever) to 100.  This fixes several issues under Windows 7 64-bit compiled with mingw-w64 in the tvedit sample with file tvedit.cc: the WinGr driver would hang at initialization; the WinNT and Win32 drivers would scroll the cursor down, but would stop scrolling up at the first function; copy and paste would cause the displayed source to jump all around.

[0001-For-TVOSf_NT-change-the-yield-from-1-forever-to-100..patch.txt](https://github.com/windoze/tvision/files/1840465/0001-For-TVOSf_NT-change-the-yield-from-1-forever-to-100.patch.txt)

**Comment by windoze** [comment]
Thanks!
Sorry I didn't test under Windows64/MinGW-w64, would you like to submit PRs for these issues?

Regards.

**Comment by guy-rouillier** [comment]
Yes, I can do that.  We will have to review my changes for compatibility 
with other compiler and OS combinations; I simply made changes as 
necessary to get the package to build on Win64 using mingw-w64 in 
64-bit.  As I noted in one of the tickets, I know at least one of my 
changes won't work on 32-bit: in regex.c, where I changed the the cast 
for register assignment from unsigned to unsigned long long.

Ugh, did some Googling on this topic, here is a discouraging discussion:

https://stackoverflow.com/questions/36952464/size-of-cpu-register

We'll have to think about this.  I just tried switching to void* and 
that didn't work, since mingw-w64 thinks high_reg and low_reg are int.

Thanks.

--
Guy Rouillier

------ Original Message ------

**Comment by guy-rouillier** [comment]
This is my first time submitting a pull request to the windoze/tvision 
repository.  How should I do that?  Create a fork of the project and 
create a pull request from the fork?  Or do you want to give me push 
access to your repo, and I can create a feature branch there?

Thanks.

--
Guy Rouillier

------ Original Message ------
From: "Guy Rouillier" <guy.rouillier@gmail.com>
To: "windoze/tvision" 
<reply@reply.github.com>
Sent: 3/23/2018 9:25:19 PM
Subject: Re[2]: [windoze/tvision] release.c For TVOSf_NT, change the 
yield from -1 (forever) to 100. (#3)

**Comment by guy-rouillier** [comment]
Submitted one quite awhile ago, did you ever receive it?  Thanks.

--
Guy Rouillier

**Comment by set-soft** [comment]
I adapted the patch using uipointer and ipointer, the definitions of the "Compat Layer" code in Turbo Vision to cast pointers.
This should work for all supported targets.

**Comment by windoze** [comment]
Sorry for the tooooooooooo late response, don't know why but I never received notification, maybe my email server was doing some nasty things...

**Comment by windoze** [comment]
The PR was merged.
Thank you very much.
